//
// ex: set ro:
// DO NOT EDIT.
// generated by smc (http://smc.sourceforge.net/)
// from file : parser.sm
//

#include "AppClass.hpp"
#include "/home/sofia/Auto_theory/lab1/parser_sm.h"

using namespace statemap;

// Static class declarations.
Map1_Start Map1::Start("Map1::Start", 0);
Map1_First_slash Map1::First_slash("Map1::First_slash", 1);
Map1_Server_slash Map1::Server_slash("Map1::Server_slash", 2);
Map1_Server_name Map1::Server_name("Map1::Server_name", 3);
Map1_Resourse_slash Map1::Resourse_slash("Map1::Resourse_slash", 4);
Map1_Resourse_name Map1::Resourse_name("Map1::Resourse_name", 5);
Map1_Resourse_end Map1::Resourse_end("Map1::Resourse_end", 6);
Map1_Catalog_slash Map1::Catalog_slash("Map1::Catalog_slash", 7);
Map1_Catalog_name Map1::Catalog_name("Map1::Catalog_name", 8);
Map1_Success Map1::Success("Map1::Success", 9);
Map1_Error Map1::Error("Map1::Error", 10);
Map1_Reset Map1::Reset("Map1::Reset", 11);

void AppClassState::on_default(parserContext& context)
{
    Default(context);
}

void AppClassState::on_digit(parserContext& context)
{
    Default(context);
}

void AppClassState::on_dollar(parserContext& context)
{
    Default(context);
}

void AppClassState::on_end(parserContext& context)
{
    Default(context);
}

void AppClassState::on_letter(parserContext& context)
{
    Default(context);
}

void AppClassState::on_slash(parserContext& context)
{
    Default(context);
}

void AppClassState::Default(parserContext& context)
{
    throw (
        TransitionUndefinedException(
            (context.getState()).getName(),
            context.getTransition()));

}

void Map1_Start::on_default(parserContext& context)
{
    AppClass& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.log_error();
        context.setState(Map1::Error);
    }
    catch (...)
    {
        context.setState(Map1::Error);
        throw;
    }
    context.getState().Entry(context);


}

void Map1_Start::on_slash(parserContext& context)
{
    AppClass& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.check_slash();
        context.setState(Map1::First_slash);
    }
    catch (...)
    {
        context.setState(Map1::First_slash);
        throw;
    }
    context.getState().Entry(context);


}

void Map1_First_slash::on_default(parserContext& context)
{
    AppClass& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.log_error();
        context.setState(Map1::Error);
    }
    catch (...)
    {
        context.setState(Map1::Error);
        throw;
    }
    context.getState().Entry(context);


}

void Map1_First_slash::on_slash(parserContext& context)
{
    AppClass& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.check_slash();
        context.setState(Map1::Server_slash);
    }
    catch (...)
    {
        context.setState(Map1::Server_slash);
        throw;
    }
    context.getState().Entry(context);


}

void Map1_Server_slash::on_default(parserContext& context)
{
    AppClass& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.log_error();
        context.setState(Map1::Error);
    }
    catch (...)
    {
        context.setState(Map1::Error);
        throw;
    }
    context.getState().Entry(context);


}

void Map1_Server_slash::on_letter(parserContext& context)
{
    AppClass& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.check_first_sym();
        ctxt.add_to_server_name();
        context.setState(Map1::Server_name);
    }
    catch (...)
    {
        context.setState(Map1::Server_name);
        throw;
    }
    context.getState().Entry(context);


}

void Map1_Server_name::on_default(parserContext& context)
{
    AppClass& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.log_error();
        context.setState(Map1::Error);
    }
    catch (...)
    {
        context.setState(Map1::Error);
        throw;
    }
    context.getState().Entry(context);


}

void Map1_Server_name::on_digit(parserContext& context)
{
    AppClass& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.add_to_server_name();
        context.setState(Map1::Server_name);
    }
    catch (...)
    {
        context.setState(Map1::Server_name);
        throw;
    }
    context.getState().Entry(context);


}

void Map1_Server_name::on_letter(parserContext& context)
{
    AppClass& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.add_to_server_name();
        context.setState(Map1::Server_name);
    }
    catch (...)
    {
        context.setState(Map1::Server_name);
        throw;
    }
    context.getState().Entry(context);


}

void Map1_Server_name::on_slash(parserContext& context)
{
    AppClass& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.check_slash();
        context.setState(Map1::Resourse_slash);
    }
    catch (...)
    {
        context.setState(Map1::Resourse_slash);
        throw;
    }
    context.getState().Entry(context);


}

void Map1_Resourse_slash::on_default(parserContext& context)
{
    AppClass& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.log_error();
        context.setState(Map1::Error);
    }
    catch (...)
    {
        context.setState(Map1::Error);
        throw;
    }
    context.getState().Entry(context);


}

void Map1_Resourse_slash::on_digit(parserContext& context)
{
    AppClass& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.valid_resourse_name();
        context.setState(Map1::Resourse_name);
    }
    catch (...)
    {
        context.setState(Map1::Resourse_name);
        throw;
    }
    context.getState().Entry(context);


}

void Map1_Resourse_slash::on_letter(parserContext& context)
{
    AppClass& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.valid_resourse_name();
        context.setState(Map1::Resourse_name);
    }
    catch (...)
    {
        context.setState(Map1::Resourse_name);
        throw;
    }
    context.getState().Entry(context);


}

void Map1_Resourse_name::on_default(parserContext& context)
{
    AppClass& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.log_error();
        context.setState(Map1::Error);
    }
    catch (...)
    {
        context.setState(Map1::Error);
        throw;
    }
    context.getState().Entry(context);


}

void Map1_Resourse_name::on_digit(parserContext& context)
{
    AppClass& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.valid_resourse_name();
        context.setState(Map1::Resourse_name);
    }
    catch (...)
    {
        context.setState(Map1::Resourse_name);
        throw;
    }
    context.getState().Entry(context);


}

void Map1_Resourse_name::on_dollar(parserContext& context)
{
    AppClass& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.valid_resourse_name();
        context.setState(Map1::Resourse_end);
    }
    catch (...)
    {
        context.setState(Map1::Resourse_end);
        throw;
    }
    context.getState().Entry(context);


}

void Map1_Resourse_name::on_end(parserContext& context)
{
    AppClass& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.log_server();
        context.setState(Map1::Success);
    }
    catch (...)
    {
        context.setState(Map1::Success);
        throw;
    }
    context.getState().Entry(context);


}

void Map1_Resourse_name::on_letter(parserContext& context)
{
    AppClass& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.valid_resourse_name();
        context.setState(Map1::Resourse_name);
    }
    catch (...)
    {
        context.setState(Map1::Resourse_name);
        throw;
    }
    context.getState().Entry(context);


}

void Map1_Resourse_name::on_slash(parserContext& context)
{
    AppClass& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.check_slash();
        context.setState(Map1::Catalog_slash);
    }
    catch (...)
    {
        context.setState(Map1::Catalog_slash);
        throw;
    }
    context.getState().Entry(context);


}

void Map1_Resourse_end::on_default(parserContext& context)
{
    AppClass& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.log_error();
        context.setState(Map1::Error);
    }
    catch (...)
    {
        context.setState(Map1::Error);
        throw;
    }
    context.getState().Entry(context);


}

void Map1_Resourse_end::on_end(parserContext& context)
{
    AppClass& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.log_server();
        context.setState(Map1::Success);
    }
    catch (...)
    {
        context.setState(Map1::Success);
        throw;
    }
    context.getState().Entry(context);


}

void Map1_Resourse_end::on_slash(parserContext& context)
{
    AppClass& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.check_slash();
        context.setState(Map1::Catalog_slash);
    }
    catch (...)
    {
        context.setState(Map1::Catalog_slash);
        throw;
    }
    context.getState().Entry(context);


}

void Map1_Catalog_slash::on_default(parserContext& context)
{
    AppClass& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.log_error();
        context.setState(Map1::Error);
    }
    catch (...)
    {
        context.setState(Map1::Error);
        throw;
    }
    context.getState().Entry(context);


}

void Map1_Catalog_slash::on_digit(parserContext& context)
{
    AppClass& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.valid_catalog_name();
        context.setState(Map1::Catalog_name);
    }
    catch (...)
    {
        context.setState(Map1::Catalog_name);
        throw;
    }
    context.getState().Entry(context);


}

void Map1_Catalog_slash::on_end(parserContext& context)
{
    AppClass& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.log_server();
        context.setState(Map1::Success);
    }
    catch (...)
    {
        context.setState(Map1::Success);
        throw;
    }
    context.getState().Entry(context);


}

void Map1_Catalog_slash::on_letter(parserContext& context)
{
    AppClass& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.valid_catalog_name();
        context.setState(Map1::Catalog_name);
    }
    catch (...)
    {
        context.setState(Map1::Catalog_name);
        throw;
    }
    context.getState().Entry(context);


}

void Map1_Catalog_name::on_default(parserContext& context)
{
    AppClass& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.log_error();
        context.setState(Map1::Error);
    }
    catch (...)
    {
        context.setState(Map1::Error);
        throw;
    }
    context.getState().Entry(context);


}

void Map1_Catalog_name::on_digit(parserContext& context)
{
    AppClass& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.valid_catalog_name();
        context.setState(Map1::Catalog_name);
    }
    catch (...)
    {
        context.setState(Map1::Catalog_name);
        throw;
    }
    context.getState().Entry(context);


}

void Map1_Catalog_name::on_end(parserContext& context)
{
    AppClass& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.log_server();
        context.setState(Map1::Success);
    }
    catch (...)
    {
        context.setState(Map1::Success);
        throw;
    }
    context.getState().Entry(context);


}

void Map1_Catalog_name::on_letter(parserContext& context)
{
    AppClass& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.valid_catalog_name();
        context.setState(Map1::Catalog_name);
    }
    catch (...)
    {
        context.setState(Map1::Catalog_name);
        throw;
    }
    context.getState().Entry(context);


}

void Map1_Catalog_name::on_slash(parserContext& context)
{
    AppClass& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.check_slash();
        context.setState(Map1::Catalog_slash);
    }
    catch (...)
    {
        context.setState(Map1::Catalog_slash);
        throw;
    }
    context.getState().Entry(context);


}

void Map1_Success::on_default(parserContext& context)
{
    AppClass& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.reset();
        context.setState(Map1::Reset);
    }
    catch (...)
    {
        context.setState(Map1::Reset);
        throw;
    }
    context.getState().Entry(context);


}

void Map1_Error::on_default(parserContext& context)
{
    AppClass& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.reset();
        context.setState(Map1::Reset);
    }
    catch (...)
    {
        context.setState(Map1::Reset);
        throw;
    }
    context.getState().Entry(context);


}

void Map1_Reset::on_default(parserContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Start);
    context.getState().Entry(context);


}

//
// Local variables:
//  buffer-read-only: t
// End:
//
