//
// ex: set ro:
// DO NOT EDIT.
// generated by smc (http://smc.sourceforge.net/)
// from file : parser.sm
//

#ifndef PARSER_SM_H
#define PARSER_SM_H


#define SMC_USES_IOSTREAMS

#include "statemap.h"

// Forward declarations.
class Map1;
class Map1_Start;
class Map1_First_slash;
class Map1_Server_slash;
class Map1_Server_name;
class Map1_Resourse_slash;
class Map1_Resourse_name;
class Map1_Resourse_end;
class Map1_Catalog_slash;
class Map1_Catalog_name;
class Map1_Success;
class Map1_Error;
class Map1_Reset;
class Map1_Default;
class AppClassState;
class parserContext;
class AppClass;

class AppClassState :
    public statemap::State
{
public:

    AppClassState(const char * const name, const int stateId)
    : statemap::State(name, stateId)
    {};

    virtual void Entry(parserContext&) {};
    virtual void Exit(parserContext&) {};

    virtual void on_default(parserContext& context);
    virtual void on_digit(parserContext& context);
    virtual void on_dollar(parserContext& context);
    virtual void on_end(parserContext& context);
    virtual void on_letter(parserContext& context);
    virtual void on_slash(parserContext& context);

protected:

    virtual void Default(parserContext& context);
};

class Map1
{
public:

    static Map1_Start Start;
    static Map1_First_slash First_slash;
    static Map1_Server_slash Server_slash;
    static Map1_Server_name Server_name;
    static Map1_Resourse_slash Resourse_slash;
    static Map1_Resourse_name Resourse_name;
    static Map1_Resourse_end Resourse_end;
    static Map1_Catalog_slash Catalog_slash;
    static Map1_Catalog_name Catalog_name;
    static Map1_Success Success;
    static Map1_Error Error;
    static Map1_Reset Reset;
};

class Map1_Default :
    public AppClassState
{
public:

    Map1_Default(const char * const name, const int stateId)
    : AppClassState(name, stateId)
    {};

};

class Map1_Start :
    public Map1_Default
{
public:
    Map1_Start(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void on_default(parserContext& context);
    virtual void on_slash(parserContext& context);
};

class Map1_First_slash :
    public Map1_Default
{
public:
    Map1_First_slash(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void on_default(parserContext& context);
    virtual void on_slash(parserContext& context);
};

class Map1_Server_slash :
    public Map1_Default
{
public:
    Map1_Server_slash(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void on_default(parserContext& context);
    virtual void on_letter(parserContext& context);
};

class Map1_Server_name :
    public Map1_Default
{
public:
    Map1_Server_name(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void on_default(parserContext& context);
    virtual void on_digit(parserContext& context);
    virtual void on_letter(parserContext& context);
    virtual void on_slash(parserContext& context);
};

class Map1_Resourse_slash :
    public Map1_Default
{
public:
    Map1_Resourse_slash(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void on_default(parserContext& context);
    virtual void on_digit(parserContext& context);
    virtual void on_letter(parserContext& context);
};

class Map1_Resourse_name :
    public Map1_Default
{
public:
    Map1_Resourse_name(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void on_default(parserContext& context);
    virtual void on_digit(parserContext& context);
    virtual void on_dollar(parserContext& context);
    virtual void on_end(parserContext& context);
    virtual void on_letter(parserContext& context);
    virtual void on_slash(parserContext& context);
};

class Map1_Resourse_end :
    public Map1_Default
{
public:
    Map1_Resourse_end(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void on_default(parserContext& context);
    virtual void on_end(parserContext& context);
    virtual void on_slash(parserContext& context);
};

class Map1_Catalog_slash :
    public Map1_Default
{
public:
    Map1_Catalog_slash(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void on_default(parserContext& context);
    virtual void on_digit(parserContext& context);
    virtual void on_end(parserContext& context);
    virtual void on_letter(parserContext& context);
};

class Map1_Catalog_name :
    public Map1_Default
{
public:
    Map1_Catalog_name(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void on_default(parserContext& context);
    virtual void on_digit(parserContext& context);
    virtual void on_end(parserContext& context);
    virtual void on_letter(parserContext& context);
    virtual void on_slash(parserContext& context);
};

class Map1_Success :
    public Map1_Default
{
public:
    Map1_Success(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void on_default(parserContext& context);
};

class Map1_Error :
    public Map1_Default
{
public:
    Map1_Error(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void on_default(parserContext& context);
};

class Map1_Reset :
    public Map1_Default
{
public:
    Map1_Reset(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void on_default(parserContext& context);
};

class parserContext :
    public statemap::FSMContext
{
public:

    explicit parserContext(AppClass& owner)
    : FSMContext(Map1::Start),
      _owner(owner)
    {};

    parserContext(AppClass& owner, const statemap::State& state)
    : FSMContext(state),
      _owner(owner)
    {};

    virtual void enterStartState()
    {
        getState().Entry(*this);
        return;
    }

    inline AppClass& getOwner()
    {
        return (_owner);
    };

    inline AppClassState& getState()
    {
        if (_state == NULL)
        {
            throw statemap::StateUndefinedException();
        }

        return dynamic_cast<AppClassState&>(*_state);
    };

    inline void on_default()
    {
        getState().on_default(*this);
    };

    inline void on_digit()
    {
        getState().on_digit(*this);
    };

    inline void on_dollar()
    {
        getState().on_dollar(*this);
    };

    inline void on_end()
    {
        getState().on_end(*this);
    };

    inline void on_letter()
    {
        getState().on_letter(*this);
    };

    inline void on_slash()
    {
        getState().on_slash(*this);
    };

private:
    AppClass& _owner;
};


#endif // PARSER_SM_H

//
// Local variables:
//  buffer-read-only: t
// End:
//
